version: '3.7'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=url
      - MYSQL_DATABASE=url
      - MYSQL_USER=url
      - MYSQL_PASSWORD=secret

  redis:
    image: redis:3.2-alpine
    command: --appendonly yes
    volumes:
      - redis-data:/data

  app:
    build:
      context: .
    image: url-shortener-app:lumen-5.4
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    depends_on: 
      - mysql
      - redis

  queue:
    image: php:7.0
    command: php artisan queue:listen
    working_dir: /var/app
    volumes:
      - .:/var/app
    depends_on: 
      - mysql
      - redis
      
volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local
