version: '3.7'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=url
      - MYSQL_DATABASE=url
      - MYSQL_USER=url
      - MYSQL_PASSWORD=secret

  redis:
    image: redis:3.2
    command: --appendonly yes
    volumes:
      - redis-data:/data

  app:
    image: php:7.0-apache
    volumes:
      - .:/var/www/app
    ports:
      - "80:80"

  queue:
    image: php:7.0
    command: php artisan queue:listen
    volumes:
      - .:/var/www/app

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local
